/** Shared theme-aware Tailwind class groups backed by CSS variables in index.css */
export const theme = {
  page: 'theme-page min-h-dvh mobile-shell overflow-x-hidden',
  pageMain: 'mx-auto max-w-7xl px-3 py-6 sm:px-6 sm:py-10 lg:px-8',
  pageMainNarrow: 'mx-auto max-w-4xl px-3 py-6 sm:px-6 sm:py-12 lg:px-8',
  pageHero: 'rounded-2xl p-5 sm:rounded-[2rem] sm:p-8',
  pageTitle: 'mt-3 text-2xl font-black sm:text-3xl md:text-4xl',
  pageSubtitle: 'mt-3 max-w-3xl text-sm leading-6 opacity-80 sm:mt-4 sm:text-base sm:leading-7',
  surface: 'theme-surface border theme-border',
  surfaceMuted: 'theme-surface-muted',
  heading: 'theme-heading',
  muted: 'theme-muted',
  border: 'theme-border border',
  hero: 'theme-hero text-white',
  heroAccent: 'theme-hero-accent',
  primaryBtn: 'theme-primary-btn min-h-11 font-bold transition hover:opacity-90 active:scale-[0.98]',
  secondaryBtn: 'theme-secondary-btn font-bold transition',
  navActive: 'theme-nav-active font-bold',
  navIdle: 'theme-nav-idle font-bold transition',
  accentSoft: 'theme-accent-soft',
  accentText: 'theme-accent-text',
  promoBanner: 'theme-promo-banner',
  input: 'theme-input w-full outline-none',
  footerPanel: 'theme-footer-panel text-white',
} as const
